services:
  whisper-webui:
    container_name: whisper-webui
    build: .
    # Removed the 'image' tag so it doesn't conflict with your local build
    
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./configs:/app/configs

    ports:
      - "7860:7860"

    stdin_open: true
    tty: true

    environment:
      - COMMANDLINE_ARGS=--server_port 7860 --server_name 0.0.0.0
      - TORCH_FORCE_WEIGHTS_ONLY_LOAD=0

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
